/**
 * Design-review harness (kept, not scrap). A scripted shell session, so the terminal
 * can be reviewed without spawning a real ConPTY.
 *
 * In its own file because the escapes matter: real ANSI (`\x1b[…m`) and real CRLFs are
 * what prove the theme's ANSI mapping and xterm's line handling, and they do not
 * survive being generated by a patch script.
 */

const ESC = "\x1b";
const CWD = "C:\\Users\\tung\\Desktop\\agentide";

/** Bold blue prompt, the way PowerShell renders one. */
const prompt = `${ESC}[1;34mPS${ESC}[0m ${CWD}> `;

const SCRIPT: [number, string][] = [
  [120, `${prompt}cargo check --all-targets\r\n`],
  [340, `    ${ESC}[1;32mChecking${ESC}[0m agentide v0.1.0 (${CWD}\\src-tauri)\r\n`],
  [520, `${ESC}[1;33mwarning${ESC}[0m: unused variable: \`root\`\r\n`],
  [545, `   ${ESC}[1;34m-->${ESC}[0m src\\pty.rs:118:9\r\n`],
  [560, `    ${ESC}[2m|${ESC}[0m\r\n`],
  [575, `${ESC}[1;34m118${ESC}[0m ${ESC}[2m|${ESC}[0m     let root = state.root();\r\n`],
  [590, `    ${ESC}[2m|${ESC}[0m         ${ESC}[1;33m^^^^${ESC}[0m help: prefix with an underscore\r\n`],
  [700, `${ESC}[1;31merror${ESC}[0m: aborting due to 1 previous error\r\n`],
  [820, `    ${ESC}[1;32mFinished${ESC}[0m \`dev\` profile in 4.71s\r\n`],
  [860, prompt],
];

/**
 * Feeds the scripted bytes to a pty output channel.
 *
 * Emits `ArrayBuffer`, not `Uint8Array`: the real channel carries output as Tauri's raw
 * body and `bridge.ts` tells output from events with `instanceof ArrayBuffer`. A view
 * fails that check and would be delivered as an event instead -- which is exactly the
 * bug this harness caught the first time.
 */
export function scriptShell(emit: (chunk: ArrayBuffer) => void) {
  const encoder = new TextEncoder();
  for (const [delay, text] of SCRIPT) {
    setTimeout(() => {
      const bytes = encoder.encode(text);
      emit(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength));
    }, delay);
  }
}
